image: publysher/hugo

before_script:
  - hugo version
  - git submodule update --init --recursive

pages:
  stage: deploy
  environment: Production
  script:
    - hugo -v -t cocoa
  artifacts:
    paths:
    - public
  only:
  - master
